### ISSUE TITLE
Какой смысл держать 80% а рублях?

### ISSUE THREAD

**Issue by vladyslav2** [codez0mb1e/resistance#1]
Все хорошо кроме совета про 80/20.
Вы точно не перепутали, тк я бы предложил абсолютно обратную стратегию, 50 в долларах, 30 в евро и 10-20 в рублях

Мне кажется ожидать того что курс отыграется сейчас опасно

**Comment by codez0mb1e** [comment]
Это соотношение *исключительно для высоколиквидных активов на Черный день*. 

Почему это кэш (наличный, а не золото), есть в этом комментарии https://habr.com/ru/post/654313/comments/#comment_24133529
Почему это не только валюта, но и рубли - в этом комментарии https://habr.com/ru/post/654313/#comment_24133515
Почему соотношении 80/20 (или похожее) - описано тут https://habr.com/ru/post/654313/comments/#comment_24133567

**Comment by Maksbyby** [comment]
Все-таки, не могу согласиться с Вашей позицией касательно 80 рубли/ 20 валюта. 
Даже, если учесть, тот факт, что правительство будет ограничивать искусственно курс, то товары наверняка будут продаваться в рублях но привязанные к курсу ( биржевому) валюты.  Я помню на пост.советском пространстве диалоги на рынках(условно):
- Сколько стоят кроссовки?
- 2 тысячи чего либо либо 20 долларов. 

Я согласен, что держать некоторую сумму в рублях надо, но я бы раздели на 30%/30%/30%

**Comment by codez0mb1e** [comment]
@vladyslav2 , @Maksbyby , понял вашу идею. Сделал уточнения к методологии выбора состава валютной корзины.
Спасибо всем за дискуссию!

**Comment by vladyslav2** [comment]
@codez0mb1e извиняюсь, пропустил нотификации.
чисто моя позиция:
80% держать в гривнах (рублях) можно только в том случае если вы точно знаете когда для чего вам они нужны и когда вы будете покупать на них валюту. Людям которые не следят за курсами валют и не знают когда покупать и продавать однозначно нужно держать 80-90% в долларах/евро и небольшую часть в рублях

Банально, по статистике рубль идет вниз и отыгрывается назад в очень редких случаях

по крайне мере я бы оставил коммертарий к совету 80/20 что риск потерять сбережения в рубле намного более высокий
