### ISSUE TITLE
Приложение Google Authenticator

### ISSUE THREAD

**Issue by MarSoft** [codez0mb1e/resistance#2]
Рекомендовано для российских брокеров переключить 2FA с Google Authenticator на SMS. Но Google Authenticator - это просто одна из реализаций протокола TOTP, который вроде как открыт и не требует связи с серверами собственно Google. Есть альтернативные клиенты (например andOTP для Android). Про серверные реализации не скажу, но там вся суть в привязке к предварительно переданному ключу и текущему времени. Так что при локдауне отвалиться не должно, на мой взгляд.

**Comment by codez0mb1e** [comment]
@MarSoft , очень правильное замечание. Уже внес исправление в статью на Хабре, в ближайшее врямя сделаю исправления в репозитории.
