### ISSUE TITLE
Газпромбанк под санкциями?

### ISSUE THREAD

**Issue by hellboy81** [codez0mb1e/resistance#26]
Требую пруфов. Есть  информация, что в Газпром и Райфайзен банках одинаковые условия перевода зарубеж: перевод физлицу возможен только при условии предоставленных документах родства (муж, жена, родители, дети), или юрлица на оплату услуг или товара. И везде надо пояснять происхождение денежных средств. Все переводы тщательно мониторят, и от суммы перевода это не зависит. Тем не менее переводы успешно проводятся

**Comment by codez0mb1e** [comment]
Да, Газпром под санкциями ([источник приведен](https://github.com/codez0mb1e/resistance/blob/main/lists.md#%D0%B1%D0%B0%D0%BD%D0%BA%D0%B8-%D0%BF%D0%BE%D0%B4-%D1%81%D0%B0%D0%BD%D0%BA%D1%86%D0%B8%D1%8F%D0%BC%D0%B8)). 

Нет никакой связи между санкциями и тем, что 'есть информация, что' возможность перевода существует/отсутствует _здесь и сейчас_. 
Зато есть связь между санкциями и рисками введения ограничений _в любой момент в будущем_.

**Comment by hellboy81** [comment]
По ссылке из википедии имеется информация, что банк попал под секторальные санкции.

В контексте статьи интересна информация, можно ли осуществлять перевод SWIFT в недружественные страны. Если да, то, с какими условиями.  Если нет, то ссылка на источник.

Термин "Банк под санкциями"  очень общий. Людей в основном интересует "SWIFT: работает или нет". 
Обычно в крипту идут сейчас люди, которые не нашли банк с работающим SWIFT для конкретного кейса
