### ISSUE TITLE
Как насчет того, чтобы подумать как можно остановить войну

### ISSUE THREAD

**Issue by ctukraine22** [codez0mb1e/resistance#3]
Уверен, что те у кого есть мозг уже разобрались с ситуацией. 
Но вам действительно не верится что от вашего бездействие люди умирают и остаются без жилья?

**Comment by sutyrin** [comment]
Это написано 8 минут назад, но почему не 8 лет назад?

**Comment by codez0mb1e** [comment]
Данный проект сфокусирован на экономических способах (они снижают риски для индивидуума), а не на политических (они важны, но увеличивают риски для индивидуума).
