### ISSUE TITLE
Get rid of putin

### ISSUE THREAD

**Issue by kyrylenko** [codez0mb1e/resistance#5]
The root cause of all the troubles you got into - is terrorist putin.
Thie madman invaded my country and right now your regular army is bombing civil districts in [Kharkiv](https://youtu.be/Pnkxnks7r0Y), Kyiv Mariupol, and several other cities. At the same time, Russia is falling down into complete isolation. Thousands of your [troops already died](https://t.me/gruz_200_rus)
The only way to stop this madness is to stop putin. So now you have 2 ways. Either you get rid of putin OR you all will continue living in North Korea v2. 
Russians! go to protests!

**Comment by codez0mb1e** [comment]
Sorry, but I don't solve **political problems** in this repository. The objective of this repository is **economics risk management**.

**Comment by kyrylenko** [comment]
Then good luck. You deserve what you get. Russians, we will neve forgive you this crime. You will pay for every killed ukrainian, for every killed child
