### ISSUE TITLE
Перечень надёжных банков

### ISSUE THREAD

**Issue by alexeych** [codez0mb1e/resistance#9]
В России существует понятие [системно-значимых банков](http://www.cbr.ru/banking_sector/credit/systembanks.html/) - тех, кому государство [не даст обанкротиться](https://ru.wikipedia.org/wiki/%D0%A1%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%BD%D0%BE_%D0%B7%D0%BD%D0%B0%D1%87%D0%B8%D0%BC%D1%8B%D0%B5_%D0%B1%D0%B0%D0%BD%D0%BA%D0%B8) и в случае проблем будет спасать за счёт бюджета.

В рейтингах самых надёжных банков России на самом верху обычно российские подразделения крупных западных банков - ЮниКредит (Италия), Росбанк (Франция), Райффайзенбанк (Австрия). Все они в России системно значимы.
В вашем списке надёжных банков они должны быть обязательно.

**Comment by codez0mb1e** [comment]
@alexeych , хорошее дополнение. 
Но прежде чем ориентироваться на этот список, как на некоторый "рейтинг гарантии", необходимо уточнить несколько важных моментов:

- есть ли какой-то закон, в соответсвии с которым ЦБ *обязан спасти* системно значимый банк? или это просто обещание, данное в спокойное время?
- на спасение каких банков из списка, хватит средств у ЦБ?
- уходил ли когда-то крупный или системно-значимый банк с российского рынка? если да, то что было с их обязательствами и активами? (если нет, то мы не знаем, что будет)
- национализация иностранных банков - опыт других стран, что вернули вкладчикам (в т.ч. валютным)?

**Comment by alexeych** [comment]
Прямой юридической обязанности ЦБ спасать системно-значимые банки, как я понял нет, но это подразумевается. В т.ч. для таких банков повышенные требования к показателям "финансового здоровья".

Но ещё более важно, что российский бизнес международных банков это малая доля их глобального бизнеса и у них полно ресурсов для оздоровления российских подразделений в случае проблем.

Вот, кстати, последний [рейтинг надёжности](https://www.forbes.ru/rating/424063-100-nadezhnyh-rossiyskih-bankov-2021-reyting-forbes) банков в РФ от Forbes.

**Comment by codez0mb1e** [comment]
> последний [рейтинг надёжности](https://www.forbes.ru/rating/424063-100-nadezhnyh-rossiyskih-bankov-2021-reyting-forbes) банков в РФ от Forbes.

Выглядит полезно. Спасибо! В ближайшее время добавлю в репу.

**Comment by codez0mb1e** [comment]
[Добавил](https://github.com/codez0mb1e/resistance/blob/main/lists.md#%D0%BF%D0%BE%D0%BB%D0%B5%D0%B7%D0%BD%D1%8B%D0%B5-%D1%81%D1%81%D1%8B%D0%BB%D0%BA%D0%B8-1). Закрываю.
